---

- name: Install required packages
  apt: name={{ item }} state=present update_cache=yes
  with_items:
  - apt-transport-https
  - ca-certificates
  - curl
  - dnsmasq
  - gnupg2
  - software-properties-common
  - systemd
  - unzip
  become: yes
