---

- name: Install Java Runtime Environment
  apt:
    name: default-jre
    state: present
    update_cache: yes
  become: yes
  tags:
  - client

- name: Add JAVA_HOME environment variable
  blockinfile:
    block: |
      ES_HEAP_SIZE=64M
      JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
    insertafter: EOF
    path: /etc/environment
    state: present
  become: yes
  tags:
  - client

- name: Enable privileged capabilities for Java
  capabilities:
    capability: cap_net_bind_service+epi
    path: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
    state: present
  become: yes
  tags:
  - client

- name: Add Elastic Stack GPG key
  apt_key:
    id: D88E42B4
    state: present
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
  become: yes

- name: Add Elastic Stack stable repository
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/6.x/apt stable main
  become: yes

- name: Install Elastic Stack client packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  become: yes
  tags:
  - client
  with_items:
  - elasticsearch
  - logstash

- name: Install Elastic Stack server packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  become: yes
  tags:
  - server
  with_items:
  - kibana

- name: Bind Kibana server host to default gateway
  blockinfile:
    block: |
      elasticsearch.url: http://172.20.20.10:9200
      server.host: 0.0.0.0
    insertafter: EOF
    path: /etc/kibana/kibana.yml
    state: present
  become: yes
  tags:
  - server

- name: Bind Elasticsearch server host to default gateway
  blockinfile:
    block: |
      network.host: 0.0.0.0
    insertafter: EOF
    path: /etc/elasticsearch/elasticsearch.yml
    state: present
  become: yes
  tags:
  - client

- name: Copy logstash pipeline configuration
  copy:
    dest: /etc/logstash/conf.d/logstash.conf
    src: logstash.conf
  become: yes
  tags:
  - client

- name: Start Elastic Stack services and enable them on reboot
  systemd:
    daemon_reload: yes
    enabled: yes
    name: "{{ item }}"
    state: started
  become: yes
  tags:
  - client
  with_items:
  - elasticsearch
  - logstash

- name: Start Elastic Stack services and enable them on reboot
  systemd:
    daemon_reload: yes
    enabled: yes
    name: "{{ item }}"
    state: started
  become: yes
  tags:
  - server
  with_items:
  - kibana

# Elastic Stack Filebeat and Metricbeat configuration
# ------------------------------------
#
# Filebeat and Metricbeat require the following products to be installed and configured:
#
# - Elasticsearch
# - Logstash
# - Kibana

- name: Wait for Elasticsearch to become available
  wait_for:
    delay: 10
    port: 9200
    state: started
  tags:
  - client

- name: Wait for Kibana to become available
  wait_for:
    delay: 10
    host: 172.20.20.11
    port: 5601
    state: started
  tags:
  - client

- name: Install Elastic Stack Filebeat
  apt:
    deb: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-6.2.2-amd64.deb
    state: present
    update_cache: yes
  become: yes
  tags:
  - client

- name: Copy Filebeat configuration file
  copy:
    backup: yes
    dest: /etc/filebeat/filebeat.yml
    src: filebeat.yml
  become: yes
  tags:
  - client

# In Elasticsearch, index templates are used to define settings and mappings that determine how
# fields should be analyzed. If the output is Logstash, you must load the template manually.
#
# Please refer to the following link for more documentation: http://bit.ly/2D5pGTp

- name: Load the index template in Elasticsearch
  command: |
    /usr/bin/filebeat setup \
    --template \
    -E output.logstash.enabled=false \
    -E 'output.elasticsearch.hosts=["localhost:9200"]'
  become: yes
  tags:
  - client

- name: Set up the Kibana dashboard for Filebeat
  command: /usr/bin/filebeat setup --dashboards
  become: yes
  tags:
  - client

- name: Restart filebeat service and enable it on reboot
  systemd:
    daemon_reload: yes
    enabled: yes
    name: filebeat
    state: restarted
  become: yes
  tags:
  - client

- name: Install Elastic Stack Metricbeat
  apt:
    deb: https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-6.2.3-amd64.deb
    state: present
    update_cache: yes
  become: yes
  tags:
  - client

- name: Copy Metricbeat configuration file
  copy:
    backup: yes
    dest: /etc/metricbeat/metricbeat.yml
    src: metricbeat.yml
  become: yes
  tags:
  - client

- name: Load the index template in Elasticsearch
  command: |
    /usr/bin/metricbeat setup \
    --template \
    -E output.logstash.enabled=false \
    -E 'output.elasticsearch.hosts=["localhost:9200"]'
  become: yes
  tags:
  - client

- name: Set up the Kibana dashboard for Metricbeat
  command: /usr/bin/metricbeat setup --dashboards
  become: yes
  tags:
  - client

- name: Restart metricbeat service and enable it on reboot
  systemd:
    daemon_reload: yes
    enabled: yes
    name: metricbeat
    state: restarted
  become: yes
  tags:
  - client
