---

- name: Create shared nomad jobs directory
  file:
    group: nomad
    owner: nomad
    path: /usr/local/share/nomad
    recurse: yes
    state: directory
  become: yes

- name: Copy nomad job files to remote host
  copy:
    dest: /usr/local/share/nomad
    group: nomad
    owner: nomad
    src: jobs
  become: yes

- name: Schedule nomad jobs
  uri:
    body: "{{ lookup('file', item) }}"
    body_format: json
    method: POST
    url: http://nomad.service.consul:4646/v1/jobs
  with_fileglob:
  - /usr/local/share/nomad/jobs/*
