---

- name: Create vault group
  group:
    name: vault
    state: present
  become: yes

- name: Create vault user
  user:
    group: vault
    name: vault
    shell: /usr/sbin/nologin
    state: present
  become: yes

- name: Download vault
  get_url:
    dest: /tmp
    url: https://releases.hashicorp.com/vault/0.8.3/vault_0.8.3_linux_amd64.zip
  register: response

- name: Move vault binary to executable directory
  unarchive:
    dest: /usr/local/bin
    mode: +x
    remote_src: yes
    src: "{{ response.dest }}"
  when: response.dest is defined
  become: yes

- name: Create vault configuration directory
  file:
    group: vault
    owner: vault
    path: /etc/vault.d
    state: directory
  become: yes

- name: Copy vault agent configuration file
  copy:
    dest: /etc/vault.d/server.hcl
    group: vault
    owner: vault
    src: server.hcl
  become: yes
  tags:
  - server

- name: Copy vault unit configuration file
  copy:
    dest: /lib/systemd/system/vault.service
    src: vault.service
  become: yes

- name: Restart vault service and enable it on reboot
  systemd:
    daemon_reload: yes
    enabled: yes
    name: vault
    state: started
  become: yes
  tags:
  - server

- include_tasks: unseal.yml
  tags:
  - server
