---

- name: Create nomad group
  group:
    name: nomad
    state: present
  become: yes

- name: Create nomad user
  user:
    name: nomad
    shell: /usr/sbin/nologin
    state: present
  become: yes

- name: Download nomad
  get_url:
    dest: /tmp
    url: https://releases.hashicorp.com/nomad/0.7.1/nomad_0.7.1_linux_amd64.zip
  register: response

- name: Move nomad binary to executable directory
  unarchive:
    dest: /usr/local/bin
    mode: +x
    remote_src: yes
    src: "{{ response.dest }}"
  become: yes
  when: response.dest is defined

- name: Create nomad configuration and data directories
  file:
    group: nomad
    owner: nomad
    path: "{{ item }}"
    recurse: yes
    state: directory
  become: yes
  with_items:
  - /etc/nomad.d
  - /var/lib/nomad/data

- name: Copy nomad agent client configuration file
  template:
    dest: /etc/nomad.d/configuration.hcl
    group: nomad
    owner: nomad
    src: client.hcl.j2
  become: yes
  tags:
  - client

- name: Copy nomad agent server configuration file
  template:
    dest: /etc/nomad.d/configuration.hcl
    group: nomad
    owner: nomad
    src: server.hcl.j2
  become: yes
  tags:
  - server

- name: Copy nomad unit configuration file
  copy:
    dest: /lib/systemd/system/nomad.service
    src: nomad.service
  become: yes

- name: Add nomad user to docker group
  user:
    groups: docker
    name: nomad
    state: present
  become: yes
  tags:
  - client

- name: Restart nomad service and enable it on reboot
  systemd:
    daemon_reload: yes
    enabled: yes
    name: nomad
    state: started
  become: yes
  tags:
  - bootstrap

- import_tasks: jobs.yml
  tags:
  - client
