Vagrant.configure("2") do |config|
  config.vm.box = "base"
  config.vm.network "forwarded_port", guest: 4646, host: 4646
  config.vm.network "forwarded_port", guest: 5601, host: 5601
  config.vm.network "forwarded_port", guest: 8200, host: 8200
  config.vm.network "forwarded_port", guest: 8500, host: 8500
  config.vm.provision "ansible_local" do |ansible|
    ansible.install = false
    ansible.playbook = "after_restart.yml"
    ansible.provisioning_path = "/home/vagrant/packer-provisioner-ansible-local"
  end
end
