---

# See https://bit.ly/2uFcfdV

- hosts: all
  connection: local
  tasks:
  - name: Install required dependencies for plugin
    homebrew:
      name: "{{ item }}"
      state: present
      update_homebrew: yes
    with_items:
    - libiconv
    - libvirt

  - name: Fetch Ruby version
    command: /opt/vagrant/embedded/bin/ruby --version
    register: response

  - set_fact:
      ruby_version: "{{ response.stdout | regex_search('(\\d{1}\\.\\d{1}\\.\\d{1})') }}"

  - name: Install vagrant-libvirt plugin
    command: vagrant plugin install vagrant-libvirt
    environment:
      CONFIGURE_ARGS: |
        with-ldflags=-L/opt/vagrant/embedded/lib \
        with-libvirt-include=/usr/local/include/libvirt \
        with-libvirt-lib=/usr/local/lib
      GEM_HOME: "{{ ansible_env.HOME }}/.vagrant.d/gems/{{ ruby_version }}"
      GEM_PATH: "{{ GEM_HOME }}:/opt/vagrant/embedded/gems"
      PATH: /opt/vagrant/embedded/bin:{{ ansible_env.PATH }}

  - name: List installed Vagrant plugins
    command: vagrant plugin list
    register: response

  - assert:
     that:
      - "'vagrant-libvirt' in response.stdout"
