---

- name: Remove old versions of Docker
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
  - docker
  - docker-engine
  - docker.io
  become: yes

- name: Add Docker GPG key
  apt_key:
    id: 0EBFCD88
    state: present
    url: https://download.docker.com/linux/ubuntu/gpg
  become: yes

- name: Add Docker stable repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
  become: yes

- name: Install Docker Community Edition
  apt:
    name: docker-ce
    state: present
    update_cache: yes
  become: yes

- name: Copy Docker daemon configuration file
  copy:
    dest: /etc/docker/daemon.json
    src: daemon.json
  become: yes
