---

- name: Check if certificate exists
  command: |
    security -q find-certificate -a -c {{ certificate }} -p /Library/Keychains/System.keychain
  become: yes
  delegate_to: 127.0.0.1
  register: response

- name: Add self-signed certificate to trusted CAs
  command: >
    security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain
    {{ playbook_dir }}/../../boxes/ansible.crt
  become: yes
  delegate_to: 127.0.0.1
  when: response.stdout == ""
