---

- name: Create docker group
  group: name=docker state=present
  become: yes

- name: Remove old versions of Docker
  apt: name={{ item }} state=removed
  with_items:
  - docker
  - docker-engine
  - docker.io
  become: yes

- name: Install required packages
  apt: name={{ item }} state=present update_cache=yes
  with_items:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg2
  - software-properties-common
  become: yes

- name: Add GPG key
  shell: curl -fsSL https://download.docker.com/linux/$(. /etc/os-release; echo "$ID")/gpg | sudo apt-key add -
  become: yes

- name: Set up the stable repository
  shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") $(lsb_release -cs) stable"
  become: yes

- name: Install the latest version of Docker CE
  apt: name=docker-ce state=present update_cache=yes
  become: yes

- name: Enable service docker
  systemd: daemon_reload=yes enabled=yes name=docker state=started
  become: yes
