---

- name: Create docker group
  group:
    name: docker
    state: present
  become: yes

- name: Remove old versions of Docker
  apt:
    name: "{{ item }}"
    state: removed
  with_items:
  - docker
  - docker-engine
  - docker.io
  become: yes

- name: Add Docker GPG key
  shell: curl -fsSL https://download.docker.com/linux/$(. /etc/os-release; echo "$ID")/gpg | sudo apt-key add -
  become: yes

- name: Add Docker stable repository
  shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") $(lsb_release -cs) stable"
  become: yes

- name: Install Docker Community Edition
  apt:
    name: docker-ce
    state: present
    update_cache: yes
  become: yes

- name: Restart docker daemon and enable it on reboot
  systemd:
    daemon_reload: yes
    enabled: yes
    name: docker
    state: started
  become: yes

- name: Copy Docker daemon configuration file
  copy:
    dest: /etc/docker/daemon.json
    src: daemon.json
  become: yes
