---

- name: Check if {{ certificate }} exists
  command: |
    security -q find-certificate -a -c {{ certificate }} -p /Library/Keychains/System.keychain
  become: yes
  register: response

- name: Add self-signed certificate to trusted CAs
  command: |
    security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain ansible.crt
  become: yes
  when: response.stdout == ""
