---

- name: Install Java Runtime Environment
  apt:
    name: default-jre
    state: present
    update_cache: yes
  become: yes

- name: Add JAVA_HOME environment variable
  lineinfile:
    insertafter: EOF
    line: "JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64"
    path: /etc/environment
    state: present
  become: yes

- name: Add Elastic Stack GPG key
  apt_key:
    id: D88E42B4
    state: present
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
  become: yes

- name: Add Elastic Stack stable repository
  shell: echo "deb https://artifacts.elastic.co/packages/6.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-6.x.list
  become: yes

- name: Install Elastic Stack packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
  - elasticsearch
  - kibana
  - logstash
  become: yes

- name: Bind Kibana server host to default gateway
  lineinfile:
    insertafter: EOF
    line: |
      server.host: "0.0.0.0"
    path: /etc/kibana/kibana.yml
  become: yes

- name: Copy syslog pipeline configuration
  copy:
    dest: /etc/logstash/conf.d/syslog.conf
    src: syslog.conf
  become: yes

- name: Start Elastic Stack services and enable them on reboot
  systemd:
    daemon_reload: yes
    enabled: yes
    name: "{{ item }}"
    state: started
  with_items:
  - elasticsearch
  - kibana
  - logstash
  become: yes
